### ISSUE TITLE
Installation using composer doesn't work due to psr-4 section being removed in composer.json

### ISSUE THREAD

**Issue by hostep** [yireo/Yireo_GoogleTagManager2#11]
Hi

We just tried installing the `master` branch using composer.
But when we try to deploy this to production, we get:
```
$ bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 54.0 MiBPHP Fatal error:  Class 'Yireo\GoogleTagManager2\Block\Generic' not found in vendor/yireo/yireo_googletagmanager2/Block/Category.php on line 16

Fatal error: Class 'Yireo\GoogleTagManager2\Block\Generic' not found in vendor/yireo/yireo_googletagmanager2/Block/Category.php on line 16
````

If we install the module manually in `app/code` everything works fine. So this must have something to do with the composer-specific installation.

I'm pretty sure the issue has been introduced in https://github.com/yireo/Yireo_GoogleTagManager2/commit/07b07cd5d1e95b761242554dbe6aa8209d845e38#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

I'm pretty sure the `psr-4` section should have remained in there, and should have been changed to:
```json
"psr-4": {
    "Yireo\\GoogleTagManager2\\": ""
},
```

Thanks for the module btw, nice work! :)

**Comment by jissereitsma** [comment]
Strange. This issue does not occur if I test this. Just to make sure, what is your Magento version? Anyway, the PSR-4 section is now back in `composer.json`. Does this fix things for you? (You might want to install this using `composer require yireo/yireo_googletagmanager2:dev-master`.)

**Comment by hostep** [comment]
I can confirm that the latest revision of the master branch (4f35a03) fixes our issue.
So it looks like the PSR-4 section is actually necessary.

Thanks for the quick fix!

**Comment by yireo** [comment]
Good to hear. There was talk on that the PSR-4 section was no longer needed. However, it seems it still is, at least for Magento 2 modules.
