### ISSUE TITLE
Wrong type casting in yireo/magento2-googletagmanager2/DataLayer/Mapper/ProductDataMapper.php 

### ISSUE THREAD

**Issue by qsolutions-pl** [yireo/Yireo_GoogleTagManager2#120]
In this file, `line 73` there is wrong type casting 

```
[2023-01-31 10:46:58] main.CRITICAL: TypeError: Argument 1 passed to Yireo\GoogleTagManager2\Util\PriceFormatter::format() 
must be of the type float, string given, called in /home/project/release/2023-01-31-08-28/vendor/yireo/magento2-googletagmanager2/DataLayer/Mapper/ProductDataMapper.php on line 73 and 
defined in /home/project/release/2023-01-31-08-28/vendor/yireo/magento2-googletagmanager2/Util/PriceFormatter.php:16
```

FinalPrice returns `string` 
`$productData['price'] = $this->priceFormatter->format($product->getFinalPrice());`

**Comment by jissereitsma** [comment]
Thanks for addressing this. Everywhere else the formatter was called while casting the relevant argument to a float .... except here. Fixed it and released 3.0.10 with it.

**Comment by qsolutions-pl** [comment]
Awesome, and thanks for great module :-)

**Comment by sprankhub** [comment]
So... We can close this? :)

**Comment by jissereitsma** [comment]
I guess so :)
