### ISSUE TITLE
Revenue seems empty in GA4 after orders are placed.

### ISSUE THREAD

**Issue by jellesiderius** [yireo/Yireo_GoogleTagManager2#124]
Hi,

We have been testing the module for a while but run into the following problem.

We used the json import from MagePal because the json import from Yireo seemed to be incomplete.
I see in Google tag manager’s debug mode that triggers and events are fired. Then I also see them in the real-time report in GA4. But I see no revenue coming up in the traffic acquisition and other reports within GA4. I do see the purchase reflected in the reports, but no revenue.

Not sure if this is something wrong with our settings though, just checking to see if this is a known issue.

![Scherm_afbeelding 2023-02-10 om 15 44 36](https://user-images.githubusercontent.com/8039493/218760439-dc4d0ca2-6fab-496f-83e7-8890883b9dd7.png)

**Comment by jissereitsma** [comment]
Did you double-check the configuration that resulted from the JSON import? See https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/TUTORIAL.md If data-layer variables are created under a slightly different name and then used in the GA4 event parameters it would explain why revenue is not showing. Also note that the revenue is calculated based on purchases. There is no revenue event sent via the data layer, only a purchase event (https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/view/frontend/layout/checkout_onepage_success.xml).

**Comment by jellesiderius** [comment]
@jissereitsma everything is working now apparently, marketing team just let me know. It was wrong configurations in Google Tag Manager i guess. I'll close this.
