### ISSUE TITLE
bug in vendor/yireo/magento2-googletagmanager2/Util/Attribute/GetAttributeValue.php on line 100

### ISSUE THREAD

**Issue by salah11172** [yireo/Yireo_GoogleTagManager2#125]
1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /var/www/magento/vendor/yireo/magento2-googletagmanager2/Util/Attribute/GetAttributeValue.php on line 100

**Comment by jissereitsma** [comment]
I've added a quick fix for this: https://github.com/yireo/Yireo_GoogleTagManager2/commit/e9cb47c109235698b480797ea890d8a846ad8ce9 However, just like your bug report, the bug fix is missing a context, explanation and confirmation. Please add some additional effort into reporting your Magento version, the extension version, the PHP version and the specific value that is causing this to go wrong. Without this, I'm not going to fix your problem.

**Comment by salah11172** [comment]
First of all, thank you for responding to this wonderful extension
magneto version 2.4.3
php version 7.4
yireo/magento2-googletagmanager2  3.0"

code
`        if (in_array($attribute->getFrontendInput(), ['textarea', 'text'])) {
            return strip_tags((string)$attributeValue);
        }`

$attribute->getFrontendInput() =  "text"
$attribute->getName() =  "sku"
$attributeValue  = "1.01E+11"

**Comment by jissereitsma** [comment]
Thanks. The line of code was indeed already known. But you say you get this error message when converting an `$attributeValue` of type `string` (the `sku`) into a yet another `string`, which will definitely not cause an error message about array-to-string conversion. Could it be another attribute of type `array` instead?

**Comment by jissereitsma** [comment]
I believe this issue is no longer there. Correct me if I'm wrong and feel free to re-open this ticket if needed.
