### ISSUE TITLE
Edit Item - Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The product that was requested doesn't exist. Verify the product and try again.

### ISSUE THREAD

**Issue by TomJ1588** [yireo/Yireo_GoogleTagManager2#134]
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The product that was requested doesn't exist. Verify the product and try again.
<pre>#1 Magento\Catalog\Model\ProductRepository\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#2 Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#3 Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php:32]
#4 Magento\Catalog\Model\ProductRepository\Interceptor->getById() called at [vendor/yireo/magento2-googletagmanager2/Util/GetCurrentProduct.php:34]
#5 Yireo\GoogleTagManager2\Util\GetCurrentProduct->get() called at [vendor/yireo/magento2-googletagmanager2/DataLayer/Tag/Product/CurrentProduct.php:48]
#6 Yireo\GoogleTagManager2\DataLayer\Tag\Product\CurrentProduct->getProduct() called at [vendor/yireo/magento2-googletagmanager2/view/frontend/templates/product/details.phtml:18]
#7 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
.......

Magento: 2.4.3-p3
PHP 7.4
Extension: 3.0.12 - Will update to 3.0.15 and test also.
Can Reproduce on 2 seperate sites.

Steps to reproduce:
Add a product to basket.
Click Mini cart to load your minicart.
Click on the pen - edit item link.
Or
View basket.
Click on the pen - edit item link.

Disabling the extension everything works as it should.
With extension enabled - exception is thrown.

**Comment by TomJ1588** [comment]
Also tested and present with v 3.0.15

**Comment by TomJ1588** [comment]
Had a chance to look this morning. 
Still Present in v 3.0.16

**Comment by TomJ1588** [comment]
Awesome, tested this morning, can confirm it has fixed the issue.

Thanks!

**Comment by jissereitsma** [comment]
Perfect. Closing this issue :)
