### ISSUE TITLE
Optimise GetProductsFromCategoryBlockPlugin

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager2#135]
Currently, `GetProductsFromCategoryBlockPlugin` blindly stores all products from the collection in an internal array. Potentially, there could be lots of products. For instance, on search result pages, we sometimes have 5000 products. Hence, this class will store 5000 products. I am not sure how smart PHP is with that, but potentially, this could also be a memory issue.

In any case, wouldn't it make more sense to apply the filtering currently done here

https://github.com/yireo/Yireo_GoogleTagManager2/blob/2f68486e71059ceb1bd25b8ff29da89686ba0407/DataLayer/Tag/Category/Products.php#L46-L48

already in `GetProductsFromCategoryBlockPlugin`?

**Comment by jissereitsma** [comment]
Definitely makes sense. I'll simply incorporate the same check in the plugin class. Releasing right now.

**Comment by sprankhub** [comment]
Thanks!
