### ISSUE TITLE
Conversion Tracking

### ISSUE THREAD

**Issue by DavidLambauer** [yireo/Yireo_GoogleTagManager2#147]
Heya,

I just installed the module in one of our shops. I followed the instructions, and so far, it works fine. I wondered why I couldn't see any conversions in Analytics. I can see the cart page or checkout success page as a page view, but nothing is marked as a conversion, nor is there information about the price of the products/cart. 

Is this something I have to configure myself in the Tag Manager, or am I missing something?

**Comment by jissereitsma** [comment]
This is actually a FAQ already :) Yes, this is something purely in Analytics (not Tag Manager). If you can see a `purchase` event in either GA or GTM, then this extension has done its job. There are some confusing tutorials out there that show how to select that `purchase` to translate into GA, and I hope that's documented one day.
