### ISSUE TITLE
Typo in Yireo\GoogleTagManager2\Block\Quote

### ISSUE THREAD

**Issue by pgrigoruta** [yireo/Yireo_GoogleTagManager2#15]
Line 35 of Yireo\GoogleTagManager2\Block\Quote reads:

`'productId' => $item->getProduct->getId(),`

This produces a notice as getProduct should have been called as a method

**Comment by jissereitsma** [comment]
Fixed in https://github.com/yireo/Yireo_GoogleTagManager2/pull/16
