### ISSUE TITLE
Debug Logs in CustomerSessionDataProvider

### ISSUE THREAD

**Issue by gaeldelmer** [yireo/Yireo_GoogleTagManager2#150]
Debugger isn't implemented in customer events

**Comment by jissereitsma** [comment]
Nice catch. I'm on the road, but because you typed in the code right here in the GitHub Issue, perhaps you could also just edit the file here on GitHub and create a Pull Request? Pull Requests are easier to create and easier to handle then comments in issue.

**Comment by jissereitsma** [comment]
Good stuff, very nice you could do that. I'll include your name in the honorary CHANGELOG :)
