### ISSUE TITLE
Issue with array unpacking operator in AddDataToCustomerSection

### ISSUE THREAD

**Issue by joachimVT** [yireo/Yireo_GoogleTagManager2#152]
Hi

I think there's an issue with in PHP 7.4 in the latest version 3.2   `AddDataToCustomerSection.php`

```
return [
    'customerLoggedIn' => 1,
    'customerId' => $customerId,
    'customerGroupId' => $customerGroup->getId(),
    'customerGroupCode' => strtoupper($customerGroup->getCode()),
    ...$customerGtmData
];
```

The problem is that the [splat operator](https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat) (array unpacking operator or ...) does not work with associative arrays in PHP 7.4.

Is it possible to use array_merge instead of unpacking operator as long as php 7.4 is supported ? 

Thanks

**Comment by jissereitsma** [comment]
Good catch. I totally overlooked this, partially because simple PHP linting does not catch this. This will be included in the next release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/87d7644a85fd683e64cfa93b429419475d757c5b
