### ISSUE TITLE
Event purchase quantity is a string instead of a int

### ISSUE THREAD

**Issue by sadlyblue** [yireo/Yireo_GoogleTagManager2#153]
Hi,

Just contacted Google and they said that the quantity is not being registered correctly. It's always 1.
They say it's because in the window.dataLayer.push({"event":"purchase", ... the "quantity":"2.0000" instead of "quantity":2

Think it should be in DataLayer/Mapper/OrderItemDataMapper.php line 60
'quantity' => (int)$orderItem->getQtyOrdered(),

Best regards

**Comment by jissereitsma** [comment]
Thanks. This is now part of the next release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/54d1e232a3d775d580aa8573064727d1a040814f 

By the way, did you know that creating a Pull Request for this change was actually easier, only requiring you to edit the file in question and then submitting it as a PR?
