### ISSUE TITLE
Support Decimal Qtys

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager2#155]
I just stumbled upon https://github.com/yireo/Yireo_GoogleTagManager2/commit/54d1e232a3d775d580aa8573064727d1a040814f, which introduces a bug IMHO. In Magento, you can have decimal quantities, so that you could e.g. order a quantity of 1.85 of a specific product. This commit rounds the qty, which it should not. What was the reason for the change? Could we still support decimal qtys?

**Comment by jissereitsma** [comment]
This was actually discussed here: https://github.com/yireo/Yireo_GoogleTagManager2/issues/153 He called Google. Well, I don't know about that, but I do know that the docs specify that the `qty` should be a number where it was a `string` earlier: https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#purchase_item However, diving into what a "number" is, I also see numbers with decimals. In otherwords, it is I guess better to cast it to a `float` instead (which is suggested to be the right return type of the method, but hey, Magento doesn't do strong typing yet).

**Comment by jissereitsma** [comment]
Included for next release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/df9b3caf5188cca9e62a8c99a25acf4443beeb67

**Comment by sprankhub** [comment]
Nice, thanks!
