### ISSUE TITLE
Encoding Issue with non-Latin1 Characters in script-pusher.phtml and Push.js

### ISSUE THREAD

**Issue by amjadm61** [yireo/Yireo_GoogleTagManager2#162]
https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/view/frontend/templates/hyva/script-pusher.phtml#L20
https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/view/frontend/web/js/push.js#L10

The script is breaking if the text contains any non-Latin1 characters in the string, like the trademark symbol (™) when encoding it to base64 using the btoa method. Therefore, the event is not being created in the dataLayer.

We may be able to fix this by using encodeURIComponent like this:
`btoa(encodeURIComponent(JSON.stringify(copyEventData)));`

**Comment by jissereitsma** [comment]
Could you comment on how it breaks things? The `bloa` method is just meant to create a simple in JS to keep track of the already existing events. Do you get an error?

**Comment by jissereitsma** [comment]
Scrap my earlier comment. I was able to reproduce this very easily my self. And I added your fix (and name) to a new release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/0a1b97015951f809b13b14268cc3f62d31df80a2

**Comment by jissereitsma** [comment]
Thanks!
