### ISSUE TITLE
Division by zero issue when showing all products per page

### ISSUE THREAD

**Issue by pgrigoruta** [yireo/Yireo_GoogleTagManager2#17]
When showing all items per page (option disabled by default), category pages throw a division by zero fatal error. This is generated in Yireo\GoogleTagManager2\Block\Category:

`$collection->setCurPage($this->getCurrentPage())->setPageSize($this->getLimit());`

Limit is set to zero in this case.

**Comment by jissereitsma** [comment]
Fixed in https://github.com/yireo/Yireo_GoogleTagManager2/pull/16
