### ISSUE TITLE
Support For Enhanced Conversions

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager2#171]
See https://support.google.com/google-ads/answer/13262500 for more information about enhanced conversions.

On the checkout success page, it would be handy to introduce a `sha256_email_address` variable into the data layer in order to be able to easily integrate enhanced conversions in GTM.

I'll send a PR in a few minutes.

**Comment by jissereitsma** [comment]
Nice one. I don't know much about enhanced conversions (yet) but this is a start.

**Comment by sprankhub** [comment]
Thanks, @jissereitsma! Could you release a new version with that change?

**Comment by jissereitsma** [comment]
Yes, definitely. Version 3.5.0 is now being released.
