### ISSUE TITLE
'add_shipping_info' & 'add_payment_info' fired second time from cart

### ISSUE THREAD

**Issue by koentjeh** [yireo/Yireo_GoogleTagManager2#174]
In version 3.4.5 the events in GoogleTagManager2 works as expected when session data such as; cookies, localstorage, sessionstorage are emptied, therefor a clean session.

After finishing the purchase, adding a new product to cart and navigation to the cart the 'add_shipping_info' & 'add_payment_info' are fired again from the cart page.

**Comment by jissereitsma** [comment]
This one fell off the wagon, but I think this is fixed now.
