### ISSUE TITLE
Cannot read properties of undefined (reading 'add_to_cart_event')

### ISSUE THREAD

**Issue by ignaciomella** [yireo/Yireo_GoogleTagManager2#181]
When adding to cart, I get this error.

The line of the issue is:

`if (typeof mageCacheStorage.cart.gtm_events[eventId] !== undefined) {`

Using Magento 2.4.6 and Hyva 1.2.3

**Comment by jissereitsma** [comment]
I've released 3.5.6 to fix this issue. Let me know if this works.

**Comment by ignaciomella** [comment]
I'm afraid not. Still there...

![image](https://github.com/yireo/Yireo_GoogleTagManager2/assets/9328631/bcfe67c8-76f2-4868-839e-824b8b56464d)

**Comment by jissereitsma** [comment]
Strange, I was not getting the same error anymore. But I can see this being an issue on your site. Could you see if 3.5.7 fixes this?

**Comment by ignaciomella** [comment]
Error gone.

Thank you Yireo!
