### ISSUE TITLE
Problem with allowed pages for view_cart event

### ISSUE THREAD

**Issue by gaeldelmer** [yireo/Yireo_GoogleTagManager2#182]
I found a problem on the multi-language stores with pathname verification in view/frontend/web/js/push.js : 
`false === metaData.allowed_pages.includes(window.location.pathname)`

With language prefix pathname is equal to "/languageCode/checkout/cart/"  and not just "/checkout/cart/".
I fixed it by replacing with :
`false === metaData.allowed_pages.some(page => window.location.pathname.includes(page))`

I don't have much time to add it right now, that's why I'm leaving it here for you. Otherwise I could add it in a few weeks.

**Comment by jissereitsma** [comment]
Indeed your solution is much more sensible when the page is a bit different. It is now ready for inclusion in the next release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/00022643d27b6da862e0861037c3f358a8ead7d0 Thanks!
