### ISSUE TITLE
property "currency" is not expected in Order Items

### ISSUE THREAD

**Issue by anvanza** [yireo/Yireo_GoogleTagManager2#189]
The order items contain the property "currency" this is not expected according to the documentation.

Code:
https://github.com/yireo/Yireo_GoogleTagManager2/blob/af4b06d5993c183ef99fce802bec589f0083e35a/DataLayer/Mapper/OrderItemDataMapper.php#L58C13-L58C58

Docs:
https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtm#purchase

**Comment by jissereitsma** [comment]
Totally agree ;) This is now fixed here: https://github.com/yireo/Yireo_GoogleTagManager2/commit/cfc7a4e3715f9e10763c08e9a9c0991ef7f16b91 ready for the next release
