### ISSUE TITLE
View_cart event triggered on every pages

### ISSUE THREAD

**Issue by GautierDig** [yireo/Yireo_GoogleTagManager2#191]
Hi,

The event view_cart is triggered on every pages even when the setting "view_cart occurrences" is set on "Cart page only".
I have the version 3.5.8 of the module. And I use the hyva theme.
I also noted that the view_cart event **only** when mini cart is expended is not working neither on hyva.

**Comment by GautierDig** [comment]
I updated to the latest version (3.6.1). I still have the issue. The view_cart event is triggered in the home page

**Comment by jissereitsma** [comment]
Thanks. Nobody addressed this issue yet, so I was not aware of any issues. A fix is now in place. Release 3.6.2 should fix this.
