### ISSUE TITLE
[Critical] Customer related data is incorrect due to cache

### ISSUE THREAD

**Issue by koenner01** [yireo/Yireo_GoogleTagManager2#20]
The customer information sent to the dataLayer can be incorrect if the page has been cached by FPC already.

**Prereq:** 

- Tested on Magento2 CE 2.1.5, 2.1.6, 2.1.7
- PHP 7.0

**Steps to reproduce:**

- Make sure the FPC is enabled (which should be the case for every webshop in production!)
- Go to a page on the webshop and look at the data sent to the layer (customerId will be 0)
- Log in
- Go to the same page as step 2 and look at the data sent to the layer (customerId is still 0)

Everything that is dynamic should not be put into a static block.
The 'easy' way out would be to make the 'googletagmanager_script' block not cacheable but this will cause every page not being able to be cached (never ever do this!). The good way to do this would be to use customerData sections in which the dynamic information is being sent to the dataLayer

**Comment by jissereitsma** [comment]
Duplicate issue: https://github.com/yireo/Yireo_GoogleTagManager2/issues/8
