### ISSUE TITLE
Tracking for add_shipping_info is not working anymore

### ISSUE THREAD

**Issue by samicoman** [yireo/Yireo_GoogleTagManager2#202]
Hi @jissereitsma,

This line:
https://github.com/yireo/Yireo_GoogleTagManager2/blob/267eaf6143c25fbccf5deedd56fa994f3f6a82da/view/frontend/requirejs-config.js#L20

was changed in this commit: https://github.com/yireo/Yireo_GoogleTagManager2/commit/e4063e10b8af729fe7f74d31a801bd92f4804f40#diff-6e7351aefbdddabe1e1fc31c4e504d112b1bd2ffb341682da845d4bb917f27e1R16

But I believe it was correct in the initial implementation. Could you explain your thought behind the change?

**Comment by jissereitsma** [comment]
The reason why the JS mixin was moved, was that the original mixin on the `shipping-save-processor.js` was calling upon the reload of customer data often too soon (before the `shipping-information` REST API call was finished), while the mixin on the `shipping-save-processor/default.js` file actually waits for the REST API call to be finished.

Could you check to see if the mixin is working? This can be done by checking for the console log message `customerData reload (shipping-save-processor-mixin.js) undefined`. If it is not there, it would explain why things are working. If so, are you aware of another `shipping-save-processor` that is added on top of the regular checkout? Most likely the `registerProcessor()` function would be called for this.
