### ISSUE TITLE
add_to_wishlist event is not fired

### ISSUE THREAD

**Issue by amjadm61** [yireo/Yireo_GoogleTagManager2#206]
The 'add_to_wishlist' event is not firing when a product is added to the wishlist.

**Comment by jissereitsma** [comment]
You probably also noticed that this was due to local storage not being refreshed. I have added a fix here: https://github.com/yireo/Yireo_GoogleTagManager2/commit/54913c24aca0a3ab877cdeaf00e6e3080ea6af1d
