### ISSUE TITLE
where can I see the Customer EAV Attributes 

### ISSUE THREAD

**Issue by jbrejning** [yireo/Yireo_GoogleTagManager2#213]
Hi, 

Thank you for a nice & clean module :-)

In Backend we have added first name and last name and email to Customer EAV Attributes, but I do not see the attributes in the datalayer. How can I test this is working?

Best regards, 
Jesper

**Comment by jochemep** [comment]
See: [https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/USAGE.md](https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/USAGE.md)

> Customer EAV Attributes: Customer attributes to include when listing customers in a specific event. Currently this is not implemented fully because of privacy regulations.

**Comment by jbrejning** [comment]
I see, can some guide me in the right direction how to implement this in Hyva Theme?

**Comment by jissereitsma** [comment]
Are we talking about the same thing here? In the code of the extension there is an event `login` that is triggered for Luma and Hyva in the same way. And for both, it is excluding the customer EAV attributes.

**Comment by jissereitsma** [comment]
Another issue however is that within Luma the initial GTM data (non-event-driven) is appended with customer details from local storage, and that's not happening in Hyva. Note that those non-event-driven data are not part of GA4. So unless you have specific need for them, you don't.

**Comment by jissereitsma** [comment]
Nonetheless, that non-GA4 part will be fixed in Hyva also: https://github.com/yireo/Yireo_GoogleTagManager2/commit/db67d6f9f1e6aa9b0122c9cfe6a61dbc48937ac3
