### ISSUE TITLE
Support Google Ads dynamic remarketing

### ISSUE THREAD

**Issue by jochemep** [yireo/Yireo_GoogleTagManager2#215]
Hi, I see on the roadmap support for Google Ads dynamic remarketing. That would be a hugely valuable addition to the module. Are there any more concrete plans for this?

For more info on the requirements in the datalayer:  https://support.google.com/tagmanager/answer/6106009?hl=en

Cheers!

**Comment by jissereitsma** [comment]
Personally, as creator of this extension, I have zero interest to add this. But if somebody is able to add a Pull Request with this functionality, I'm happy to merge it!
