### ISSUE TITLE
Hyva checkout - broken header

### ISSUE THREAD

**Issue by ofrankowska** [yireo/Yireo_GoogleTagManager2#224]
In [1.1.4](https://gitlab.hyva.io/hyva-checkout/checkout/-/compare/1.1.3...1.1.4)[1.1.4](https://gitlab.hyva.io/hyva-checkout/checkout/-/compare/1.1.3...1.1.4) header in hyva checkout was improved:

> Previously the checkout used the `checkout` page layout.  
  This was changed to `1column` to provide better styling and improved compatibility with the Hyvä theme out-of-the-box.  

This module breaks header because in `hyva_checkout_index_index` layout is set to `checkout`.

I suggest removing `layout="checkout"` from the file.

**Comment by jissereitsma** [comment]
OMG, absolutely! Somebody else added this and it slipt through the code review. This will be fixed in the next release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/8773014153484410aee00d8486d324c8aae06e01

**Comment by jissereitsma** [comment]
This should be fixed with the latest versions. If not, feel free to reopen.
