### ISSUE TITLE
Purchase event triggered on canceled order. 

### ISSUE THREAD

**Issue by JoostWan** [yireo/Yireo_GoogleTagManager2#227]
1. Place an order using a payment method such as iDeal through Multisafepay.
2. Cancel the payment on the bank's page; you will be redirected back to the shop with the cart intact.
3. At this moment, the purchase event is triggered on the event sales_order_place_after.

The order state is, at that moment, pending_payment, and a few seconds later, it will be set to canceled.

https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/etc/frontend/events.xml#L32

Is it possible to show the purchase tag/event only on the `checkout_onepage_success` page.

**Comment by jissereitsma** [comment]
The only solution I can think of that makes sense is to trigger the event only if the order is not canceled. Because if the order is set to `pending_payment` and the event `sales_order_place_after` is used, then this event should fire without visiting the `checkout_onepage_success` page ...

**Comment by jissereitsma** [comment]
This change is now included in 3.9.3.

**Comment by jissereitsma** [comment]
I'm closing this ticket, assuming it is solved. Let me know if it is not.
