### ISSUE TITLE
empty phrases used in toOptionArray functions

### ISSUE THREAD

**Issue by Ruben-Winant** [yireo/Yireo_GoogleTagManager2#228]
The following files contain empty phrases in the **toOptionArray** methods which might introduce errors when using other modules [like fe, the Phpro translations module](https://github.com/phpro/phpro-mage2-module-translations )
- Model/Config/Source/CategoryAttributes.php
- Model/Config/Source/CustomerAttributes.php
- Model/Config/Source/ProductAttributes.php

I would suggest to simply set it as '' if you're not intending to translate anything.
```php
$options = [['value' => '', 'label' => '']];
```

**Comment by jissereitsma** [comment]
Agreed - it makes more sense to not add translation: https://github.com/yireo/Yireo_GoogleTagManager2/commit/aa0f9639106bf85836b4dd80e810788e9e54daca
