### ISSUE TITLE
CSP issues for Magento 2.4.7+

### ISSUE THREAD

**Issue by jemoon** [yireo/Yireo_GoogleTagManager2#230]
Seems that from Magento 2.4.7 onwards CSP isn't working in Report Mode on payment pages (admin and checkout pages). 

Quote from Release Notes:

`The default CSP configuration for payment pages for Commerce Admin and storefront areas is now restrict mode. For all other pages, the default configuration is report-only mode. In releases prior to 2.4.7, CSP was configured in report-only mode for all pages.`

In order to fix that problem all inline js from this module should be rendered through secure renderer so proper nonces will be added...

<img width="1769" alt="Screenshot 2024-04-14 at 21 01 05" src="https://github.com/yireo/Yireo_GoogleTagManager2/assets/3430741/9f599200-f1f9-4a41-95de-353505edc8d5">

**Comment by jissereitsma** [comment]
Even though the PR was good already, I've decided to go a totally different route: https://github.com/yireo/Yireo_GoogleTagManager2/commit/fc8fc70ecf77c31b20e3d23209346483ac0fafb0

The PR was wrapping inline scripts everywhere (except for the Hyva scripts, WIP) with the `$secureRenderer`. But with a multiline script this quickly becomes cumbersome. Adding a HEREDOC syntax seems to have its own issues. So instead, I went for an approach where the original block-with-script is actually wrapped in a parent block (class `\Yireo\GoogleTagManager2\Block\InlineScriptParent`) that simply renders its child, but stripping the `<script>` tag and piping everything through the secure renderer (or its dummy). To my opinion, this makes the code a lot more readable, thus maintainable - especially with all of the inline JS for Hyva.

This seems to be working fine!

Cc: @stevensagaar @jemoon @hostep @nige-one What do you think?

**Comment by hostep** [comment]
Nice, cool idea!

And it makes the frontend files indeed a lot cleaner and easier to maintain, which is always a good thing.
