### ISSUE TITLE
item_list_name on PLP

### ISSUE THREAD

**Issue by Linek** [yireo/Yireo_GoogleTagManager2#232]
Hi @jissereitsma 

On the PLP you are implementing parameter item_list_name which is always a first category of the product (getFirstByProduct).

However when I check other implementations on other e-commerces, this is usually the name or path of the current PLP, so in the GA4 reports you can measure which categories have a better click through rate.

What do you think about changing this parameter to use current category instead of first product category?

**Comment by jissereitsma** [comment]
Sounds good to me. Are you able to make a PR for this? I'm currently swamped.

**Comment by jissereitsma** [comment]
This change is now included in 3.9.3.
