### ISSUE TITLE
Price in add_to_cart event datails always the cheapest simple variant

### ISSUE THREAD

**Issue by hansvereyken** [yireo/Yireo_GoogleTagManager2#233]
When adding a configurable product to the cart (add_to_cart), the event data contains the price of the cheapest simple product linked to the configurable product, not the price of simple product that was added.

This can be fixed by changing the following line
https://github.com/yireo/Yireo_GoogleTagManager2/blob/ba2212c9aab434405cb2d53f7204d392e870aca5/DataLayer/Mapper/ProductDataMapper.php#L83
`(float)$product->getPriceInfo()->getPrice(FinalPrice::PRICE_CODE)->getValue()`
to:
`(float)$product->getFinalPrice()`

**Comment by jissereitsma** [comment]
Thanks. This is now committed here, ready for the next release: https://github.com/yireo/Yireo_GoogleTagManager2/commit/7391e4788175611f40f6732742eb6e5b15753538

**Comment by samicoman** [comment]
The code was like that a while back and the issue I had, it was returning the wrong price (currency) for multi-store setup. See: https://github.com/yireo/Yireo_GoogleTagManager2/commit/523cd144811c3e055d34f23c470f56f56824824a

So, it needs further investigation.
