### ISSUE TITLE
Type Error in class AddCspInlineScripts with the Hyva Checkout

### ISSUE THREAD

**Issue by michelheitbrink** [yireo/Yireo_GoogleTagManager2#237]
In version 3.9.0, an error occurs when selecting a payment method. This happens in combination with Magewire.

```
TypeError: Yireo\GoogleTagManager2\Plugin\AddCspInlineScripts::afterToHtml(): 
Argument #2 ($html) must be of type string, null given
```

**Comment by jissereitsma** [comment]
I've released 3.9.1 to try to fix this. Does this work for you? https://github.com/yireo/Yireo_GoogleTagManager2/commit/52954998c5daa233d13904b056030e19e20b24a1

**Comment by michelheitbrink** [comment]
Works perfectly

**Comment by jissereitsma** [comment]
Pfew! :)
