### ISSUE TITLE
Google Tag Manager only works on product and category pages

### ISSUE THREAD

**Issue by SanderAtom** [yireo/Yireo_GoogleTagManager2#24]
Homepage, cart, checkout, cms pages, etc only produce this error in the console:
`https://www.googletagmanager.com/gtm.js?id=undefined`

Any idea's?

**Comment by jissereitsma** [comment]
Which version did you install?

**Comment by SanderAtom** [comment]
Version 0.3.1

**Comment by jissereitsma** [comment]
The current release is 0.3.3. Could you first upgrade to see if that works?

**Comment by SanderAtom** [comment]
Unless I'm missing something but 0.3.2 isn't there and 0.3.3 only has a text change in the readme. I will update it though and let you know.

**Comment by SanderAtom** [comment]
Yep that fixed it thanks!
