### ISSUE TITLE
New version tag

### ISSUE THREAD

**Issue by ssx** [yireo/Yireo_GoogleTagManager2#241]
@jissereitsma can we get a new version tagged when you get a chance, I need this commit:

https://github.com/yireo/Yireo_GoogleTagManager2/commit/68f4efa84a39958f3dd057a2e380d4234c2f421a

**Comment by jissereitsma** [comment]
This was still waiting other tasks, that are now completed. Note that it's a bit more than just tagging :)

**Comment by ssx** [comment]
I thought it may be - appreciate the work though Jisse!
