### ISSUE TITLE
Purchase Event Not Firing

### ISSUE THREAD

**Issue by Dani-A-Dias** [yireo/Yireo_GoogleTagManager2#245]
Hello!

I'm facing an issue and was hoping you could provide some guidance. I’m currently working on tracking for an online store, and although I’ve set up tracking for several stores before, this is my first time working with Magento.

My client has requested that I use your extension in their Magento shop. They were previously using a different extension, but it lacked the necessary events for comprehensive tracking. I’ve tested most of the events, and they all seem to be working except for the purchase event. With the previous plugin, the purchase event was tracked directly in GA4.

I’m not seeing anything in the console—no failed events or the event itself. It’s not triggering my tags, nor is it appearing in the GA4 debug view. Google Ads isn’t recognizing the event either, and there’s nothing in the DataLayer Checker.

I’m at a bit of a loss and unsure of what I might be doing wrong. Any tips or suggestions would be greatly appreciated! My knowledge in this area is quite limited, so perhaps there’s something specific I should check.

Apologies if this seems vague.

Thank you in advance!

**Comment by jissereitsma** [comment]
Which version of this module are you using?

**Comment by Dani-A-Dias** [comment]
Hello! Thank you so much for replying! I don't have access to that information, but I believe it's the latest one since it was installed just a few days ago. Magento is version 2.4.2 if it helps.

**Comment by jissereitsma** [comment]
Many versions come out regularly. Could you please double-check? Any kind of fix will require proper access to the Magento site anyway. Without knowing the exact version, I wouldn't know what to fix either.

**Comment by Dani-A-Dias** [comment]
Version 3.9.7
Unfortunately, gaining better access to the site might be challenging. I currently only have sufficient access to configure the extensions and make minimal changes.

I’ll discuss this with the client to see what they decide. If they grant me additional access or find a way to streamline the troubleshooting process without too much back and forth, I’ll update this post. Otherwise, I’ll close the issue to avoid taking up more of your time. I genuinely appreciate the help you’ve provided, and I don’t want to impose further.

**Comment by jissereitsma** [comment]
I understand. Version 3.9.7 is indeed the last version.

**Comment by jissereitsma** [comment]
Glad to hear this completed. However, could you perhaps comment on why the ticket was closed?

**Comment by Dani-A-Dias** [comment]
Of course! I am sorry for taking so long to reply.

My client decided to not grant me additional access. But I can tell that the problem was something related to the extra payment methods, the files had to be renamed in order to work. Can't give more details, since I wasn't a part of the solution, but if someone else finds him/herself in this situation, check the file names for extra payment methods! 

Thank you so very much for your attention!
