### ISSUE TITLE
Event purchase does not work

### ISSUE THREAD

**Issue by gabi77** [yireo/Yireo_GoogleTagManager2#249]
In version 3.9.8 with magento 2.4.7-p2 in php8.3.10

the event purchase does not work anymore. On the previous version everything seems good and correct to me.

**Comment by jissereitsma** [comment]
Thanks. Actually, with other sites it is still working. So this seems to be something more specific for your own project. Could you share further details? Did you double-check with logging enabled in the console that the purchase event is fired or not fired? Also, which checkout are you using? Also, what do you have configured for "Orders states for purchase event"? Please help anyone help you.

**Comment by jissereitsma** [comment]
I'm closing this because of no reply, plus the fact that new releases improve this.
