### ISSUE TITLE
3.9.12 release should be a Major version change instead of a patch release.

### ISSUE THREAD

**Issue by thomas-kl1** [yireo/Yireo_GoogleTagManager2#251]
Regarding changes in this release: https://github.com/yireo/Yireo_GoogleTagManager2/compare/3.9.11...3.9.12

The 3.9.12 introduce a BIC (a class is moved). It may breaks developments that relies on this class.

**Comment by jissereitsma** [comment]
Yes, technically, if you would consider all the code in this extension worthy of maintaining as something to be backward compatible. For me personally, I don't see the reason why anyone would want to modify the config classes of the extension without notifying me. So I don't see this as a breaking change that is semver-worthy.
