### ISSUE TITLE
Error getting store name

### ISSUE THREAD

**Issue by woakley** [yireo/Yireo_GoogleTagManager2#3]
Notice: Undefined property: Yireo\GoogleTagManager2\Block\Quote::$scopeConfig in /Yireo/GoogleTagManager2/Block/Generic.php on line 179 [] []

Might be related to this?
Broken reference: No element found with ID 'checkout.header.wrapper'. [] []

**Comment by jissereitsma** [comment]
This is kind of stupid. We fixed this a while ago, but never released it properly. The new release 0.2.5 is available now and does include this fix!
