### ISSUE TITLE
Section updates in the checkout is through the roof

### ISSUE THREAD

**Issue by koenner01** [yireo/Yireo_GoogleTagManager2#36]
Every keystroke in the checkout is refreshing the the yireo sections;
This is producing an unresponsive checkout sometimes (because of the number of queued refreshes)

It's this part in view/frontend/web/js/generic.js that's causing the massive requests amount
```
var monitorCheckout = function () {
    var checkout = customerData.get('checkout-data');
    checkout.subscribe(function (updatedCart) {
        customerData.reload(['yireo-gtm-quote', 'yireo-gtm-order']);
    });
    return true;
};
```

I think the only thing that we actually need to track during the checkout is if the quote totals get updated which can be done with:
```

define([
    'jquery',
    'underscore',
    'Magento_Customer/js/customer-data',
    'Magento_Checkout/js/model/quote'
], function ($, _, customerData, quote) {
...
var monitorCheckout = function () {
    quote.totals.subscribe(function (newValue) {
        customerData.reload(['yireo-gtm-quote', 'yireo-gtm-order']);
    });
    return true;
};
...
```

**Comment by jissereitsma** [comment]
I think I agree. Could you make a PR for this?

**Comment by jissereitsma** [comment]
Later versions have added improvements on this. Closing because of lack of reply. Feel free to re-open if needed
