### ISSUE TITLE
Config location

### ISSUE THREAD

**Issue by vseager** [yireo/Yireo_GoogleTagManager2#43]
Does the configuration for this module have to be under the "Sales" section? It doesn't relate to sales, and Tag Manager can be used for anything. It would make more sense to be located under "Services".

**Comment by jissereitsma** [comment]
Maybe. But the cores "Google API" (showing settings for Adwords) is also under "Sales". So perhaps, it should just be under "Sales > Google API"?

**Comment by fritzmg** [comment]
@jissereitsma but those settings are related to actual sales processes - while the Google Tag Manager is something more general.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. The section has been moved to a "Yireo" tab quite some time ago already.
