### ISSUE TITLE
Compatibility 2.3

### ISSUE THREAD

**Issue by fwegberts** [yireo/Yireo_GoogleTagManager2#46]
Hi,

Is this extension compatibile with magento 2.3?

**Comment by jissereitsma** [comment]
Yes, we believe so. Please note that I recommend to disbelieve extension developers and instead rely on `composer` to do the dependency management. If the extension is installed through `composer` while its `composer.json` file indeed reflects its dependencies, then it works.

**Comment by jissereitsma** [comment]
Closing because of lack of reply. Feel free to re-open if needed
