### ISSUE TITLE
E-commerce data not tracked in Google Analytics

### ISSUE THREAD

**Issue by pixelive** [yireo/Yireo_GoogleTagManager2#49]
Hello,

First of all, nice extension 👍 

I have a small problem with it. We had correct e-commerce tracking in Google Analytics for one day, but suddenly it stopped working. We also did an upgrade to version 0.3.16 but still no tracking of e-commerce data in GA. I used both insertion methods observer and xml layout for several days. And also see that the dataLayer variable is filled with transaction information. All the other tracking works fine.

We have e-commerce tracking enabled at the GA settings in Google Tag Manager. And trigger the Google Analytics tag at DOM ready, maybe this is too early? Or do we need a custom trigger / tag for e-commerce tracking (for this extension)? 

I use the same Google Tag Manager and Google Analytics setup with DuracellTomi's Google Tag Manager for WordPress for WooCommerce and the e-commerce tracking works fine there. 

But maybe it is an event problem or something?

Thanks in advance!

**Comment by jissereitsma** [comment]
To support e-commerce tracking in GTM, a GTM extension needs to add an `ecommerce` layer to the `dataLayer`. This extension does not support this (yet). Isn't this simply the problem? The feature that you are using, is actually not part of this extension?

**Comment by pixelive** [comment]
Nevermind had to fix my transaction tag. Works now. Thanks anyway.

**Comment by jissereitsma** [comment]
Thanks. Do you mean you needed to fix it in the GTM console at Google? Or was it reconfigured somewhere else?

**Comment by pixelive** [comment]
In Google GTM :)

**Comment by jissereitsma** [comment]
Cool. Just to know for sure. Thanks.
