### ISSUE TITLE
Installation problem with magento 2.1 

### ISSUE THREAD

**Issue by Nym77** [yireo/Yireo_GoogleTagManager2#5]
Dears, 
first of all thank you for developing this extension.

I am trying to install it in a fresh new installation of magento 2.1 with php7 using MAMP

Unfortunately nothing appear in the configuration.php and the command lines are executed without any feedback (both with and without sudo privileges) 

Commands: 
 sudo php -c /Applications/MAMP/bin/php/php7.0.10/conf/php.ini -f bin/magento module:enable Yireo_GoogleTagManager2 
 sudo php -c /Applications/MAMP/bin/php/php7.0.10/conf/php.ini -f bin/magento setup:upgrade

Directory where I have the files 
/Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2

Do you have any advice?

**Comment by jissereitsma** [comment]
Does the command `bin/magento module:status` list all modules including or excluding our module? Why don't you install this module via composer, which is the recommended way for developers?

**Comment by Nym77** [comment]
@jissereitsma As i just installed the module I wanted to give you feedback as a "normal user" and not a developer. 

The module is not in the list. Maybe because there is no registration.php in the module itself 
http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/component-registration.html

could that be?

**Comment by jissereitsma** [comment]
The `registration.php` is there in our sources: https://github.com/yireo/Yireo_GoogleTagManager2/tree/master/source

**Comment by Nym77** [comment]
@jissereitsma ty 

I copied the content of the folder ./source in ./  and re-run the installation commands and not it works. 

in my case the ./ is /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2 

Hope that this may helps someone in a similar situation
