### ISSUE TITLE
composer.json lacks module version 

### ISSUE THREAD

**Issue by speedupmate** [yireo/Yireo_GoogleTagManager2#50]
currently this extension does not define any version information so you could add a 

`"version": "yourversion",`

to composer.json so it can be required by version or compared or made as a dependency in composer. 

I can see that setup_version is defined in module.xml file but this is not a version info composer can read (or meant for defining m2 version information as this is a setup version)

**Comment by sprankhub** [comment]
composer reads the versions from the git tags. A `version` property in `composer.json` is not a good idea. From the [composer docs](https://getcomposer.org/doc/04-schema.md#version):

> The version of the package. In most cases this is not required and should be omitted (see below).

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.

> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

**Comment by jissereitsma** [comment]
It's a difficult issue. It is not recommended by composer itself. And it used to be a bad thing in Magento as well. However, modifying the `etc/module.xml` file for version bumps is bad as well, because of the impact on db upgrades it makes.

Currently, it **could** (carefully phrasing) be a best practice to include the `version` in `composer.json`. 

The reason for this is that sometimes modules are used as ZIP packages without composer deployment, and in those cases, the version still needs to be clearly visible somewhere.

**Comment by sprankhub** [comment]
I would second that for modules, which cannot be included via VCS / Packagist. In this case, it makes sense to have the `version` property in the `composer.json`. However, speaking about a module which is publicly available on GitHub with perfect tags like this one, I do not see any value at all.

**Comment by speedupmate** [comment]
I agree that this is not fun etc but all m2 devs face the fact that their magento-extensions are  just dropped to app/code or installed as local artefacts from local paths set up as composer channels, theres no VCS in this case to get the version information from. As a support person, good luck finding out what version is used in such cases.  

https://getcomposer.org/doc/04-schema.md#version and is suggested to have this in "TAG" . But the  only reason given there is: 

> Specifying the version yourself will most likely end up creating problems at some point due to human error. 

I can't see any reason why this same error can't happen on tagging things without having a iterator set up somewhere.

**Comment by jissereitsma** [comment]
@speedupmate Exactly. So, however it is not perfect, a `version` should be part of the JSON file. Currently, my deployment chain is still setup wrongly to extract the version from the `etc/module.xml` (which causes me to bump the `setup_version` again and again). However, I will switch to using the version from `composer.json` instead anyway. I've now released 0.3.17 which ships this fix of the `composer.json` file. Thanks for pointing it out.

**Comment by speedupmate** [comment]
\Magento\Framework\Module\PackageInfo has a method getVersion to retrieve composer version of a package . I usually display this invormation in admin as first info in extension configuration section. Makes it easy for merchants to get the version information.
