### ISSUE TITLE
Extension states compatibility with M2.1 but requires M2.2+

### ISSUE THREAD

**Issue by scottsb** [yireo/Yireo_GoogleTagManager2#51]
The README and composer.json indicate that this is compatible with Magento 2.1; however, it requires this class, which was only added in Magento 2.2:

`Magento\Framework\View\Element\Block\ArgumentInterface`

This was introduced recently in #47.

**Comment by jissereitsma** [comment]
Thanks for pointing this out. Actually, the XML layout `argument name="viewModel" xsi:type="object"` does not work either in Magento 2.1 or older. I'll need to look into how to fix this. Possibly, the PR will be undone and a fix release is made for 2.1. However, after this, the original PR will be merged back in and this will lead to a major release that is no longer compatible with Magento 2.1.

**Comment by scottsb** [comment]
Yes, we didn't get past the initial error after doing a `composer update`, so I don't know what other incompatibilities may be around.

**Comment by jissereitsma** [comment]
Version 0.3.18 is now out, which removes this feature, so it requires under Magento 2.1 again. However, I'm now proceeding with a major release 1.0.0 which ships this anyway.
