### ISSUE TITLE
How to manage google analytics

### ISSUE THREAD

**Issue by CharanjeetE** [yireo/Yireo_GoogleTagManager2#54]
Hi 
I need help how can I check if the google analytics is working in the magento 2 store if this extension is enabled. How to confirm if google analytics is working.

**Comment by jissereitsma** [comment]
Unfortunately this is out of scope of this extension. Once GTM loads in Magento, you will need to follow the instructions of Google to set things up in the GTM dashboard. The only thing you can do in Magento is enabled the extension, done.
