### ISSUE TITLE
Simplify section handling via intercepting original sections

### ISSUE THREAD

**Issue by jissereitsma** [yireo/Yireo_GoogleTagManager2#58]
Remove new GTM sections and add same information to existing sections like `cart` and `customer` via intercepting the relevant PHP methods using plugins.

**Comment by peterjaap** [comment]
Wasn't this done in 1.1.0? https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/CHANGELOG.md#110---2019-11-23

**Comment by jissereitsma** [comment]
Yes! Thanks for spotting this.
