### ISSUE TITLE
Magento setup:di:compile Error

### ISSUE THREAD

**Issue by Nym77** [yireo/Yireo_GoogleTagManager2#6]
I am suing magento 2.1.2 with MAMP and PHP7 

If i run the following command: 
Magento setup:di:compile

I obtain the following error 

Compilation was started.
Interception cache generation...

Errors during compilation:
	Yireo\GoogleTagManager2\Block\Category
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Category in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Category.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
\Magento\Framework\View\LayoutInterface already exists in context object
	Yireo\GoogleTagManager2\Block\Generic
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Generic in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Generic.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
	Yireo\GoogleTagManager2\Block\Order
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Order in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Order.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 3
Errors during compilation:
	Yireo\GoogleTagManager2\Block\Category
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Category in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Category.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
\Magento\Framework\View\LayoutInterface already exists in context object
	Yireo\GoogleTagManager2\Block\Generic
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Generic in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Generic.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
	Yireo\GoogleTagManager2\Block\Order
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Order in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Order.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 3

Errors during compilation:
	Yireo\GoogleTagManager2\Block\Category
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Category in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Category.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
\Magento\Framework\View\LayoutInterface already exists in context object
	Yireo\GoogleTagManager2\Block\Generic
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Generic in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Generic.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
	Yireo\GoogleTagManager2\Block\Order
		Incorrect dependency in class Yireo\GoogleTagManager2\Block\Order in /Applications/MAMP/htdocs/magento2/app/code/Yireo/GoogleTagManager2/Block/Order.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 3

**Comment by yireo** [comment]
Hello,

Could you let us know the version of our module that you are trying to 
install? All of the errors occurred in the 0.1.X version of our module, 
but have been fixed about 6 months ago and the current version of our 
module is version 0.2.5.

Regards,

Jisse Reitsma
Yireo - yireo.com - reliable extensions & professional services for 
Magento and Joomla!
Magento Performance Insights - simple calculations can lead to solid 
advice - https://www.yireo.com/mpi
Programming Joomla Plugins book - a must-read for any Joomla developer - 
https://www.yireo.com/pjp
Zend Z-Team Member - http://www.zend.com/en/company/community/the-z-team
twitter: #yireo / facebook: http://facebook.com/yireo
linkedin: http://www.linkedin.com/profile/view?id=21532424
google+: https://plus.google.com/u/0/114906815855957969844/posts

**Comment by Nym77** [comment]
@yireo ty for the feedback 
 in am using the last current official release version 0.2. 
I will have a look at your last release so I can give you a better feedback

**Comment by Nym77** [comment]
@yireo Happy to confirm you that the problem is solved in version 0.25 using my setup too

**Comment by jissereitsma** [comment]
Could I suggest then that in the future, instead of raising a support issues, you simply first upgrade? We tend to fix issues fast by releasing new versions. But it is a waste of time, if we are still spending time on issues that have been fixed ago. This is a free extension, so help us support you by simply using the latest version when running into troubles. This probably counts for any free software package.
