### ISSUE TITLE
Remove legacy ViewModels

### ISSUE THREAD

**Issue by jissereitsma** [yireo/Yireo_GoogleTagManager2#60]
Remove pre-Magento-2.2 ViewModels and increase major version if needed.

**Comment by peterjaap** [comment]
Isn't this done in 2.1.0? https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/CHANGELOG.md#removed

**Comment by jissereitsma** [comment]
Yes! Thanks for spotting this.
