### ISSUE TITLE
Does this module enhance or replace the out of the box Google Tag Manager Option in M2.3 Commerce?

### ISSUE THREAD

**Issue by gavinhoman** [yireo/Yireo_GoogleTagManager2#62]
In the latest docs for 2.3 there is a Google Tag manager option within Stores > Config > Sales > Google API > Google Analytics

Is this an alternative or better solution as it's part of core Magento now?

https://docs.magento.com/m2/ee/user_guide/marketing/google-tag-manager.html

**Comment by jissereitsma** [comment]
If you want to use the core tags, just use the core. I'm not an expert in M2 Commerce at all and I'm bad in selling my own extension. But I would say that in essence the core tags are included in our extension as well. However, a quick glimpse in the Yireo doc (https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/USAGE.md) shows me that customer tags are included in the Yireo extension. but I don't see that in the docs of the core version. There might be numerous of those slight differences. But if the client doesn't use those additional tags, don't offer thm ;)

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.

Note that a new version of this Yireo GoogleTagManager (v3) was released with GA4 support, full checkout support and completely event-driven. It could fix the issue that you were having.
