### ISSUE TITLE
Does it push ecommerce Tags / events?

### ISSUE THREAD

**Issue by amenk** [yireo/Yireo_GoogleTagManager2#65]
I had a look at window.dataLayer, there seems to be nor notion of `ecommerce`.

Google Tag Manager suggest such tags:

https://developers.google.com/tag-manager/enhanced-ecommerce#checkout

Can you shed some light on this?

**Comment by jissereitsma** [comment]
That's correct. Ecommerce is currently not included. The following is included: https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/USAGE.md

**Comment by amenk** [comment]
Are there plans to add that?

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.

Note that a new version of this Yireo GoogleTagManager (v3) was released with GA4 support, full checkout support and completely event-driven. It could fix the issue that you were having.
