### ISSUE TITLE
Incompatibility with Google Optimize standard implementation

### ISSUE THREAD

**Issue by scottsb** [yireo/Yireo_GoogleTagManager2#66]
We ran into an issue with the module where tags in GTM were fired, but all the data layer properties were undefined. We traced it to the fact that we had recently installed Google Optimize on the site according to the standard instructions.

What is not obvious from the Google Optimize instructions is that doing so actually triggers the instantiation of GTM. In keeping with the instructions for Optimize, this was added high on the page, in the `<head>`. This is beneficial for Optimize so that A/B tests can be applied to the page with a minimum of "jerk" where the user sees the non-test version before the test applies.

Unfortunately, because it is in the `<head>` and because it triggers GTM, it means that the data layer is not loaded by the time the GTM "page load" events fire. When this module is used by itself, the data layer is populated by this time since the module doesn't call GTM until after the global `dataLayer` variable is setup.

Our solution is to add the following as a theme override of `custom.phtml` so that the asynchronous data layer push performed by the module has a named event attached. We can then change our GTM tags to trigger on the new `datalayer.load` event instead.

    <?php
    /** @var \Yireo\GoogleTagManager2\Block\Category $block */
    $helper = $block->getHelper();
    ?>
    <?php if($helper->isEnabled()) : ?>
        <?php $block->addAttribute('event', 'datalayer.load'); ?>
    <?php endif; ?>

Is that a solution that you'd want to consider building into the module itself (obviously not through `custom.phtml`, but in some other spot)? At a minimum it may be worth documenting this potential issue in the README.

**Comment by jissereitsma** [comment]
This ticket was never picked up upon in the past. Sorry for that. In the mean time, a new version of this Yireo GoogleTagManager (v3) was released with GA4 support, full checkout support and completely event-driven. It could fix the issue that you were having. The issue you were having might have been related to the old GA3 implementation. Note that the GTM module activates all data layer information now via events. Additional events for Google Optimize might be needed.

**Comment by jissereitsma** [comment]
I'm closing this issue now because it has been inactive for so long. Feel free to re-open if this is still bugging.
