### ISSUE TITLE
GA4 usage

### ISSUE THREAD

**Issue by seansan** [yireo/Yireo_GoogleTagManager2#73]
When looking at GA4 and wanting to implement all 'normal' page views, for instance `view_item_list` we are accessing `categoryProducts` for a list of products. Though, the fields in the json list are different from the spec.

https://developers.google.com/tag-manager/ecommerce-ga4#measure_productitem_list_viewsimpressions

How would we tackle list views and products views using GA4?

![image](https://user-images.githubusercontent.com/652395/109666128-2fe42800-7b6f-11eb-9dbc-df2906db9249.png)

**Comment by jissereitsma** [comment]
This extension offers a basic implementation of GTM. Additional layers need to be added by PHTML overrides or hooking in a different way into the code. The answer you seek requires in-depth customization which is unfortunately beyond the scope of the open source project here.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.

Note that a new version of this Yireo GoogleTagManager (v3) was released with GA4 support, full checkout support and completely event-driven. It could fix the issue that you were having.
