### ISSUE TITLE
AdBlocker causing that the generic.js file does not load and to display some JS errors

### ISSUE THREAD

**Issue by toh82** [yireo/Yireo_GoogleTagManager2#77]
Even if cookies are not accepted it breaks the checkout
```
InsertScriptFilter.js:32 GET https://highlite.lh/static/version1624441844/frontend/Magento/luma/de_DE/Yireo_GoogleTagManager2/js/generic.js net::ERR_BLOCKED_BY_CLIENT

require.js:166 Uncaught Error: Script error for: Yireo_GoogleTagManager2/js/generic
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
```

**Comment by toh82** [comment]
Update on this. The checkout does not break entirely, this was caused by a other script which build on top. 

But still, why does a ad blocker block loading of the generic.js file, this seems super strange to me

**Comment by jissereitsma** [comment]
Unfortunately, I'm not sure how I could be of help. I don't know about the script `InsertScriptFilter`. Plus your description is about "a ad blocker block" without specifying which. As of yet, I'm unable to duplicate any issue. Nobody else is reporting this issue. So I'm doubting this is even related to this Magento extension. Perhaps your AdBlocker is configured to block Google Analytics? I'm closing this issue as of yet. Please re-open if you are eager to help debugging things to the bottom, with as a result an improvement of the Magento extension.

**Comment by toh82** [comment]
actually it does not matter which ad blocker. But specific I tested it with uBlock Origin.

I think anyway you can't do anything about it since it seems that the script is blocked because it's loading path contains the string "GoogleTagmanager". Means fixing this would most likely result in renaming the complete Module to something abstract.

At least this is what I found trough a bit of playing around. 

The big Problem with this is, that if someone extends the generic.js file with a mixin, the requirejs explodes, since the generic.js was blocked from loading.

**Comment by jissereitsma** [comment]
Did you check to see if something like the following helps? https://support.magento.com/hc/en-us/articles/360025397571-Checkout-pages-not-loading-when-ad-blocker-is-enabled I think this issue arises with any (!) kind of JS script that is determined by any (!) kind of blocking mechanism (adblocker, firewall), and therefore should not be solved with this extension, but with RequireJS itself.

**Comment by toh82** [comment]
yes, yes and yes. ;) the solution in the linked post is already merged in magento2 wo technically this issu should be cought already. Guess have to digg deeper into this.

**Comment by jissereitsma** [comment]
Looking at the patch and comparing it with Magento 2.4.2, it seems the file `lib/web/mage/requirejs/resolver.js` has moved on since. For instance, the method `isRegistered` is no longer there, and part of the code has been moved to `isRejected`. However, the code of `isRejected` seems to assume that the module was loaded but rejected by RequireJS, while I think there would be need for a check where the module was never loaded in the first place ... Or something.

**Comment by toh82** [comment]
@jissereitsma thanks for you help on this, I'll play around with the code and what you wrote looks really promising. Have to check how the stuff works on the places you mentioned. 

Maybe it's a thing for `src/lib/web/mage/requirejs/mixins.js` like checking if a module was loaded proper before applying the mixin.
