### ISSUE TITLE
Class Yireo\GoogleTagManager2\Helper\Debug located in ./vendor/yireo/magento2-googletagmanager2/Util/Debug.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by tuyennn** [yireo/Yireo_GoogleTagManager2#81]
Version 2.1.2

Here the Warning Deprecation Notice

```
Class Yireo\GoogleTagManager2\Helper\Debug located in ./vendor/yireo/magento2-googletagmanager2/Util/Debug.php does not comply with psr-4 autoloading standard
```
Possible to do refactor the Namespace

**Comment by jissereitsma** [comment]
Thanks, this is now fixed: https://github.com/yireo/Yireo_GoogleTagManager2/commit/793348a67b7529171de3d3fbd994fa00bc50047a Note that the class is not used anyway at this moment, so nothing will stop working and therefore, a new release will not be made.
