### ISSUE TITLE
2.4.3 support?

### ISSUE THREAD

**Issue by dehaan-jeroen** [yireo/Yireo_GoogleTagManager2#82]
Installating the module in a Magento 2.4.3 installation returns a requirements error.

Is the module compatible with Magento 2.4.3? If so, can the composer.json be updated to allow installation on 2.4.3.?

**Comment by jissereitsma** [comment]
Actually, many have already upgraded to Magento 2.4.3 plus GoogleTagManager without issues. So perhaps you are misinterpreting the composer error? The answer to whether the module is compatible with 2.4.3 is YES. But this is something that can be fact-checked pretty easily and to prevent this question from asked again, here's the simple check that everyone should make: Every single composer requirement matches with the actual composer packages of 2.4.3 (https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/composer.json#L19). For instance, the framework requirement of `^101.2|^102.0|^103.0` can be double-checked with `composer show | grep magento/framework` which shows `103.0.2` under Magento 2.4.3. This leads to the conclusion that your reporting of the compatibility is not the real issue, the composer error issue is the actual issue. It is better to post the actual composer error, so we can shortcut discussions.

**Comment by dehaan-jeroen** [comment]
Turns out we copied the wrong command from the installation documentation (`composer require yireo/magento2-googletagmanager2:^1.0`).

**Comment by jissereitsma** [comment]
Thanks. That command was actually part of an update procedure from `^0.0`. The actual installation section mentioned the same command without versioning. I will remove the entire section to avoid confusion.
