### ISSUE TITLE
Incompatibility with Amasty_Xlanding version 1.8.8

### ISSUE THREAD

**Issue by norgeindian** [yireo/Yireo_GoogleTagManager2#83]
Since we updated to the latest Amasty_Xlanding version, we found a lot `NoSuchEntityExceptions: No entry with id = 0` in our exception.log.
After debugging, we found the following call stack:

```
<pre>#1 Magento\Catalog\Model\CategoryRepository->get(0, NULL) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#2 Magento\Catalog\Model\CategoryRepository\Interceptor->___callParent('get', array(0, NULL)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#3 Magento\Catalog\Model\CategoryRepository\Interceptor->Magento\Framework\Interception\{closure}(0) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Catalog\Model\CategoryRepository\Interceptor->___callPlugins('get', array(0), array(array('Amasty_Shopby::C...'))) called at [generated/code/Magento/Catalog/Model/CategoryRepository/Interceptor.php:32]
#5 Magento\Catalog\Model\CategoryRepository\Interceptor->get(0) called at [vendor/yireo/magento2-googletagmanager2/ViewModel/Category.php:64]
#6 Yireo\GoogleTagManager2\ViewModel\Category->getCurrentCategory() called at [vendor/yireo/magento2-googletagmanager2/view/frontend/templates/category.phtml:17]
```
It turns out, that Amasty adds the handle `catalog_category_view` to its landing pages, but they don't have any valid category ID as parameter.

This way, `\Yireo\GoogleTagManager2\ViewModel\Category::getCurrentCategory` throws the exception.
It would be great if this could be handled somehow.

**Comment by jissereitsma** [comment]
It sounds like Amasty didn't understand the meaning of the `catalog_category_view` handle. A fix is now added to the Yireo GoogleTagManager2 module templates. Could you upgrade to 2.1.3 to see if it works for you?

**Comment by norgeindian** [comment]
@jissereitsma , I'm with you, but I thought the chances are better that we find a fix here than explaining Amasty the meaning of the handle.
So thanks a lot for your fix, works perfectly.
